export default {
  INIT_STORE: 'INIT_STORE',
  CLEAR_STORE: 'CLEAR_STORE',
  INIT_USER_OAUTH: 'INIT_USER_OAUTH',
  SET_USER_OAUTH: 'SET_USER_OAUTH',
  CLEAR_USER_OAUTH: 'CLEAR_USER_OAUTH',
  INIT_CART_LIST: 'INIT_CART_LIST',
  SET_CART_LIST: 'SET_CART_LIST',
  ADD_CART_LIST: 'ADD_CART_LIST',
  UPDATE_CART_LIST: 'UPDATE_CART_LIST',
  BATCH_DELETE_CART_LIST: 'BATCH_DELETE_CART_LIST',
  CLEAR_CART_LIST: 'CLEAR_CART_LIST'
}
